version: "3.9"
services:
  icecast:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - icecast:/data/icecast
    networks:
      - icecast-network
    hostname: icecast

networks: 
  icecast-network: 
    external: true 

volumes:
  icecast:
